# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-21 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=60)),
                ('permalink', models.CharField(max_length=12, unique=True)),
                ('bodytext', models.TextField(blank=True, verbose_name=b'Page Content')),
            ],
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('desc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_reg.Course')),
            ],
        ),
    ]
