# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-21 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='course_reg.Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='description',
            name='desc',
            field=models.CharField(max_length=500),
        ),
    ]
